export const DEFAULT_EXERCISES = [
  { name: "Barbell Back Squat", muscleGroup: "Legs" },
  { name: "Barbell Front Squat", muscleGroup: "Legs" },
  { name: "Romanian Deadlift", muscleGroup: "Legs" },
  { name: "Leg Press", muscleGroup: "Legs" },
  { name: "Leg Curl", muscleGroup: "Legs" },
  { name: "Leg Extension", muscleGroup: "Legs" },
  { name: "Walking Lunges", muscleGroup: "Legs" },
  { name: "Hip Thrust", muscleGroup: "Legs" },
  { name: "Calf Raise", muscleGroup: "Legs" },
  { name: "Conventional Deadlift", muscleGroup: "Pull" },
  { name: "Sumo Deadlift", muscleGroup: "Pull" },
  { name: "Barbell Row", muscleGroup: "Pull" },
  { name: "Pendlay Row", muscleGroup: "Pull" },
  { name: "Dumbbell Row", muscleGroup: "Pull" },
  { name: "Cable Row", muscleGroup: "Pull" },
  { name: "Lat Pulldown", muscleGroup: "Pull" },
  { name: "Pull Up", muscleGroup: "Pull" },
  { name: "Chin Up", muscleGroup: "Pull" },
  { name: "Face Pull", muscleGroup: "Pull" },
  { name: "Barbell Curl", muscleGroup: "Arms" },
  { name: "Dumbbell Curl", muscleGroup: "Arms" },
  { name: "Hammer Curl", muscleGroup: "Arms" },
  { name: "Incline Dumbbell Curl", muscleGroup: "Arms" },
  { name: "Barbell Bench Press", muscleGroup: "Push" },
  { name: "Incline Barbell Bench Press", muscleGroup: "Push" },
  { name: "Dumbbell Bench Press", muscleGroup: "Push" },
  { name: "Incline Dumbbell Bench Press", muscleGroup: "Push" },
  { name: "Cable Fly", muscleGroup: "Push" },
  { name: "Overhead Press", muscleGroup: "Push" },
  { name: "Dumbbell Shoulder Press", muscleGroup: "Push" },
  { name: "Lateral Raise", muscleGroup: "Push" },
  { name: "Tricep Pushdown", muscleGroup: "Arms" },
  { name: "Skull Crusher", muscleGroup: "Arms" },
  { name: "Close Grip Bench Press", muscleGroup: "Arms" },
  { name: "Overhead Tricep Extension", muscleGroup: "Arms" },
  { name: "Dip", muscleGroup: "Push" },
  { name: "Push Up", muscleGroup: "Push" },
  { name: "Plank", muscleGroup: "Core" },
  { name: "Ab Wheel Rollout", muscleGroup: "Core" },
  { name: "Cable Crunch", muscleGroup: "Core" },
];

export const WORKOUT_TYPES = [
  { value: "PUSH", label: "Push" },
  { value: "PULL", label: "Pull" },
  { value: "LEGS", label: "Legs" },
  { value: "UPPER", label: "Upper" },
  { value: "LOWER", label: "Lower" },
  { value: "ARMS", label: "Arms" },
  { value: "CUSTOM", label: "Custom" },
];

export const FEELING_OPTIONS = [
  { value: "STRONG", label: "Strong" },
  { value: "NORMAL", label: "Steady" },
  { value: "FATIGUED", label: "Fatigued" },
];

export const REACTION_TYPES = [
  { value: "STRONG_SESSION", label: "Fire", icon: "flame" },
  { value: "PR", label: "PR", icon: "trophy" },
  { value: "GOOD_WORK", label: "Respect", icon: "bolt" },
];
