// Animated figure library for the guided stretch player.
//
// Routines are generated by the coach, so the drill names are free-form — we
// can never guarantee a hand-drawn illustration for whatever it invents. So
// this file defines a CLOSED set of poses and three ways to land on one:
//
//   1. The coach emits a `pose` slug from the enum below (the reliable path —
//      the enum is listed verbatim in the trainer prompt).
//   2. Failing that, keyword-match the drill's name (KEYWORDS).
//   3. Failing that, fall back to a generic figure for the item's modality,
//      so EVERY step still shows something moving.
//
// A pose is pure geometry: joint coordinates in a 120x100 viewBox with the
// floor at y=92, plus optional props and a motion hint. Two frames means a
// two-beat loop (the player cross-fades them); one frame means a still figure
// animated by `motion` / `swing` / `spin`. Keeping this as data — not JSX —
// means components/StretchFigure.tsx is the single renderer and adding a drill
// is a dozen lines here.

export type Pt = [number, number];

// shoulder/hip → elbow/knee → hand/foot
type Limb = [Pt, Pt, Pt];

export type PoseFrame = {
  head: Pt;
  headR?: number;
  neck: Pt;
  hip: Pt;
  // Control point making the spine a quadratic curve instead of a straight
  // line — what lets cat/cow arch and round, and child's pose fold over.
  spineCtl?: Pt;
  armA?: Limb;
  armB?: Limb;
  legA?: Limb;
  legB?: Limb;
};

export type PoseProp =
  | { kind: "floor" }
  | { kind: "wall"; x: number }
  | { kind: "roller"; at: Pt; r?: number }
  // A bar drawn between the two hands of whichever frame is showing.
  | { kind: "handbar" };

export type PoseDef = {
  frames: [PoseFrame] | [PoseFrame, PoseFrame];
  props?: PoseProp[];
  // Whole-figure idle motion. "breathe" is the default resting animation for a
  // static hold; "roll" slides the body along a foam roller.
  motion?: "breathe" | "sway" | "roll";
  // Limbs that rotate continuously (arm circles) or swing back and forth
  // (leg swings), pivoting on their first joint.
  spin?: ("armA" | "armB")[];
  swing?: ("legA" | "legB")[];
};

export const STRETCH_POSES = [
  // static holds
  "hamstring-hinge",
  "figure-4",
  "hip-flexor-lunge",
  "pigeon",
  "child-pose",
  "chest-doorway",
  "overhead-triceps",
  "neck-lateral",
  "calf-wall",
  "butterfly",
  "seated-twist",
  "supine-twist",
  "cobra",
  "side-bend",
  // dynamic mobility
  "cat-cow",
  "worlds-greatest",
  "leg-swing",
  "arm-circles",
  "hip-cars",
  "open-book",
  "deep-squat",
  "glute-bridge",
  "shoulder-pass-through",
  // loaded / active end-range work
  "bar-hang",
  "crab-bridge",
  "down-dog",
  "bretzel",
  "ninety-ninety",
  "butchers-block",
  "crawl",
  // soft tissue
  "foamroll-quad",
  "foamroll-hamstring",
  "foamroll-itband",
  "foamroll-back",
  "foamroll-calf",
  "ball-glute",
  // breathing
  "breathing-supine",
  "breathing-seated",
  // generic fallbacks, one per modality
  "generic-static",
  "generic-dynamic",
  "generic-foamroll",
  "generic-breathing",
] as const;

export type StretchPose = (typeof STRETCH_POSES)[number];

const POSE_SET = new Set<string>(STRETCH_POSES);

const FLOOR: PoseProp[] = [{ kind: "floor" }];

export const POSES: Record<StretchPose, PoseDef> = {
  // ---- static holds ------------------------------------------------------
  // Note on limb emphasis: legA/armA draw at full strength and legB/armB at
  // 45% (the "far side" of the body). Whichever limb carries the meaning of
  // the drill — the leg being stretched, the arm doing the reaching — belongs
  // in the A slot, or the pose reads as a faint smudge.

  // Standing hamstring stretch: back leg tall, front leg long with the heel
  // down, torso hinged forward over it.
  "hamstring-hinge": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [74, 32],
        neck: [67, 40],
        hip: [48, 54],
        armA: [[65, 42], [75, 58], [84, 74]],
        legA: [[48, 54], [67, 70], [87, 85]],
        legB: [[48, 54], [45, 73], [43, 92]],
      },
    ],
  },

  // Supine figure-4: ankle crossed over the opposite thigh, hands pulling the
  // support thigh toward the chest.
  "figure-4": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [16, 74],
        neck: [28, 80],
        hip: [62, 86],
        armA: [[29, 80], [47, 70], [65, 61]],
        legA: [[62, 86], [92, 68], [72, 56]],
        legB: [[62, 86], [77, 48], [64, 78]],
      },
    ],
  },

  // Half-kneeling hip flexor / quad stretch, back knee down, tall torso, one
  // arm reaching overhead to open the front of the hip.
  "hip-flexor-lunge": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [54, 22],
        neck: [54, 31],
        hip: [54, 55],
        armA: [[52, 33], [47, 18], [45, 5]],
        armB: [[56, 34], [66, 46], [75, 62]],
        legA: [[54, 55], [76, 72], [76, 92]],
        legB: [[54, 55], [34, 86], [19, 91]],
      },
    ],
  },

  // Pigeon: front shin folded across the body, back leg long behind, chest up.
  pigeon: {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [51, 50],
        neck: [56, 59],
        hip: [63, 84],
        armA: [[55, 61], [48, 74], [44, 88]],
        legA: [[63, 84], [37, 85], [70, 90]],
        legB: [[63, 84], [86, 88], [106, 91]],
      },
    ],
  },

  // Child's pose: hips back over the heels, spine long, arms reaching away.
  "child-pose": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [34, 84],
        headR: 6,
        neck: [45, 79],
        hip: [82, 66],
        spineCtl: [64, 70],
        armA: [[46, 79], [32, 84], [18, 89]],
        legA: [[82, 66], [74, 88], [93, 90]],
      },
    ],
  },

  // Doorway pec stretch: forearm on the frame, chest rotated away from it.
  "chest-doorway": {
    motion: "breathe",
    props: [{ kind: "floor" }, { kind: "wall", x: 101 }],
    frames: [
      {
        head: [55, 24],
        neck: [53, 33],
        hip: [50, 55],
        armA: [[55, 36], [78, 37], [97, 31]],
        armB: [[50, 36], [44, 51], [42, 67]],
        legA: [[50, 55], [47, 74], [45, 92]],
        legB: [[50, 55], [57, 74], [61, 92]],
      },
    ],
  },

  // Overhead triceps stretch: elbow pointed at the ceiling, hand down the
  // spine, opposite hand pulling the elbow over.
  "overhead-triceps": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [58, 24],
        headR: 7,
        neck: [57, 34],
        hip: [56, 56],
        armA: [[49, 36], [39, 11], [59, 15]],
        armB: [[64, 36], [76, 22], [46, 12]],
        legA: [[56, 56], [50, 74], [48, 92]],
        legB: [[56, 56], [63, 74], [67, 92]],
      },
    ],
  },

  // Lateral neck stretch: head tipped, same-side hand resting over the ear.
  "neck-lateral": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [52, 22],
        headR: 7,
        neck: [60, 33],
        hip: [60, 58],
        armA: [[52, 36], [37, 15], [53, 7]],
        armB: [[69, 36], [73, 52], [75, 68]],
        legA: [[60, 58], [53, 75], [51, 92]],
        legB: [[60, 58], [67, 75], [69, 92]],
      },
    ],
  },

  // Calf stretch into a wall: back leg straight, heel driven into the floor.
  "calf-wall": {
    motion: "breathe",
    props: [{ kind: "floor" }, { kind: "wall", x: 103 }],
    frames: [
      {
        head: [64, 32],
        neck: [58, 39],
        hip: [45, 53],
        armA: [[58, 41], [79, 38], [99, 40]],
        armB: [[57, 43], [78, 45], [99, 47]],
        legA: [[45, 53], [31, 72], [18, 90]],
        legB: [[45, 53], [63, 66], [68, 90]],
      },
    ],
  },

  // Butterfly / seated adductor: soles together, knees relaxed toward the floor.
  butterfly: {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [60, 19],
        headR: 7,
        neck: [60, 31],
        hip: [60, 63],
        armA: [[51, 34], [44, 56], [53, 79]],
        armB: [[69, 34], [76, 56], [67, 79]],
        legA: [[60, 63], [38, 76], [58, 84]],
        legB: [[60, 63], [82, 76], [62, 84]],
      },
    ],
  },

  // Seated spinal twist: knee crossed up, opposite elbow braced outside it,
  // trailing hand planted behind. Two frames deepen the rotation.
  "seated-twist": {
    props: FLOOR,
    frames: [
      {
        head: [61, 20],
        headR: 7,
        neck: [60, 32],
        hip: [58, 68],
        armA: [[51, 35], [63, 44], [79, 49]],
        armB: [[69, 35], [82, 50], [81, 67]],
        legA: [[58, 68], [75, 53], [46, 73]],
        legB: [[58, 68], [36, 73], [15, 77]],
      },
      {
        head: [69, 22],
        headR: 7,
        neck: [63, 33],
        hip: [58, 68],
        armA: [[54, 36], [66, 46], [82, 50]],
        armB: [[72, 36], [85, 52], [83, 68]],
        legA: [[58, 68], [75, 53], [46, 73]],
        legB: [[58, 68], [36, 73], [15, 77]],
      },
    ],
  },

  // Supine twist: knees dropped across the body, opposite arm opened wide.
  "supine-twist": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [19, 73],
        neck: [31, 79],
        hip: [63, 85],
        armA: [[31, 78], [31, 62], [31, 46]],
        armB: [[32, 82], [42, 88], [53, 91]],
        legA: [[63, 85], [79, 62], [96, 74]],
        legB: [[63, 86], [82, 67], [99, 79]],
      },
    ],
  },

  // Cobra / low-back extension: hips heavy, chest pressed up off the floor.
  cobra: {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [35, 45],
        neck: [45, 55],
        hip: [74, 89],
        spineCtl: [59, 74],
        armA: [[45, 57], [43, 74], [42, 90]],
        legA: [[74, 89], [92, 91], [109, 91]],
      },
    ],
  },

  // Standing side bend / lat stretch: overhead reach, ribs opened to one side.
  "side-bend": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [50, 21],
        headR: 7,
        neck: [56, 32],
        hip: [64, 58],
        spineCtl: [58, 45],
        armA: [[51, 34], [41, 23], [30, 15]],
        armB: [[66, 35], [75, 47], [69, 57]],
        legA: [[64, 58], [60, 75], [58, 92]],
        legB: [[64, 58], [70, 75], [72, 92]],
      },
    ],
  },

  // ---- dynamic mobility --------------------------------------------------

  // Cat-cow: one quadruped base, spine sagging with the head up, then rounding
  // with the head tucked.
  "cat-cow": {
    props: FLOOR,
    frames: [
      {
        head: [22, 48],
        neck: [34, 57],
        hip: [83, 57],
        spineCtl: [58, 76],
        armA: [[34, 59], [32, 75], [31, 90]],
        legA: [[83, 57], [86, 74], [87, 90]],
      },
      {
        head: [28, 72],
        neck: [35, 60],
        hip: [83, 57],
        spineCtl: [58, 38],
        armA: [[35, 62], [32, 75], [31, 90]],
        legA: [[83, 57], [86, 74], [87, 90]],
      },
    ],
  },

  // World's greatest stretch: deep lunge with the hand down, then rotate the
  // chest open and reach for the ceiling.
  "worlds-greatest": {
    props: FLOOR,
    frames: [
      {
        head: [51, 31],
        neck: [51, 40],
        hip: [51, 60],
        armA: [[53, 42], [59, 63], [63, 88]],
        armB: [[49, 42], [45, 65], [43, 88]],
        legA: [[51, 60], [75, 68], [78, 92]],
        legB: [[51, 60], [33, 78], [14, 92]],
      },
      {
        head: [51, 31],
        neck: [51, 40],
        hip: [51, 60],
        armA: [[53, 42], [61, 25], [69, 8]],
        armB: [[49, 42], [45, 65], [43, 88]],
        legA: [[51, 60], [75, 68], [78, 92]],
        legB: [[51, 60], [33, 78], [14, 92]],
      },
    ],
  },

  // Leg swings: stand tall, one leg pendulums freely from the hip.
  "leg-swing": {
    swing: ["legA"],
    props: FLOOR,
    frames: [
      {
        head: [54, 22],
        neck: [54, 31],
        hip: [54, 53],
        armA: [[48, 34], [36, 42], [24, 46]],
        armB: [[60, 34], [72, 42], [84, 46]],
        legA: [[54, 53], [62, 71], [70, 88]],
        legB: [[54, 53], [52, 73], [50, 92]],
      },
    ],
  },

  // Arm circles: both arms sweep a full turn from the shoulder.
  "arm-circles": {
    spin: ["armA", "armB"],
    props: FLOOR,
    frames: [
      {
        head: [60, 19],
        headR: 7,
        neck: [60, 31],
        hip: [60, 58],
        armA: [[51, 36], [35, 38], [19, 40]],
        armB: [[69, 36], [85, 38], [101, 40]],
        legA: [[60, 58], [53, 75], [51, 92]],
        legB: [[60, 58], [67, 75], [69, 92]],
      },
    ],
  },

  // Hip CARs: stand on one leg and drive the other knee around its full circle.
  "hip-cars": {
    swing: ["legA"],
    props: FLOOR,
    frames: [
      {
        head: [54, 22],
        neck: [54, 31],
        hip: [54, 55],
        armA: [[60, 34], [70, 45], [78, 51]],
        armB: [[48, 34], [36, 45], [26, 51]],
        legA: [[54, 55], [73, 47], [80, 65]],
        legB: [[54, 55], [52, 74], [50, 92]],
      },
    ],
  },

  // Open book: side-lying thoracic rotation, top arm sweeping across the body
  // and then all the way open behind.
  "open-book": {
    props: FLOOR,
    frames: [
      {
        head: [20, 66],
        neck: [33, 73],
        hip: [69, 83],
        armA: [[33, 72], [49, 62], [65, 53]],
        legA: [[69, 83], [93, 81], [91, 62]],
      },
      {
        head: [20, 66],
        neck: [33, 73],
        hip: [69, 83],
        armA: [[33, 72], [24, 56], [15, 40]],
        legA: [[69, 83], [93, 81], [91, 62]],
      },
    ],
  },

  // Deep bodyweight squat hold: hips low between the feet, chest tall.
  "deep-squat": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [48, 37],
        neck: [52, 47],
        hip: [58, 73],
        armA: [[52, 49], [64, 58], [73, 53]],
        legA: [[58, 73], [84, 76], [67, 92]],
        legB: [[58, 74], [88, 79], [71, 92]],
      },
    ],
  },

  // Glute bridge: hips drive up off the floor and lower back down.
  "glute-bridge": {
    props: FLOOR,
    frames: [
      {
        head: [17, 82],
        neck: [29, 87],
        hip: [60, 86],
        armB: [[29, 88], [43, 91], [56, 92]],
        legA: [[60, 86], [84, 56], [84, 91]],
      },
      {
        head: [17, 82],
        neck: [29, 87],
        hip: [60, 60],
        spineCtl: [43, 77],
        armB: [[29, 88], [43, 91], [56, 92]],
        legA: [[60, 60], [84, 56], [84, 91]],
      },
    ],
  },

  // Shoulder pass-through: wide grip on a stick, sweeping from the hips to
  // overhead and back.
  "shoulder-pass-through": {
    props: [{ kind: "floor" }, { kind: "handbar" }],
    frames: [
      {
        head: [60, 19],
        headR: 7,
        neck: [60, 31],
        hip: [60, 58],
        armA: [[51, 35], [40, 45], [28, 55]],
        armB: [[69, 35], [80, 45], [92, 55]],
        legA: [[60, 58], [53, 75], [51, 92]],
        legB: [[60, 58], [67, 75], [69, 92]],
      },
      {
        head: [60, 19],
        headR: 7,
        neck: [60, 31],
        hip: [60, 58],
        armA: [[51, 35], [40, 21], [28, 8]],
        armB: [[69, 35], [80, 21], [92, 8]],
        legA: [[60, 58], [53, 75], [51, 92]],
        legB: [[60, 58], [67, 75], [69, 92]],
      },
    ],
  },

  // ---- loaded / active end-range ------------------------------------------

  // Dead hang from a bar: arms straight overhead, shoulders relaxed up toward
  // the ears, whole body long. Feet stay clear of the floor.
  "bar-hang": {
    motion: "sway",
    props: [{ kind: "floor" }, { kind: "handbar" }],
    frames: [
      {
        head: [60, 30],
        headR: 7,
        neck: [60, 41],
        hip: [60, 64],
        armA: [[52, 44], [50, 26], [50, 9]],
        armB: [[68, 44], [70, 26], [70, 9]],
        legA: [[60, 64], [57, 76], [56, 88]],
        legB: [[60, 64], [64, 76], [65, 88]],
      },
    ],
  },

  // Crab bridge / reverse plank: hands behind, chest open, hips pressed up to
  // parallel. Two frames so the hips visibly drive up and lower.
  "crab-bridge": {
    props: FLOOR,
    frames: [
      {
        head: [34, 62],
        neck: [40, 70],
        hip: [64, 82],
        armA: [[40, 70], [33, 81], [28, 92]],
        legA: [[64, 82], [86, 74], [90, 92]],
      },
      {
        head: [30, 52],
        neck: [38, 58],
        hip: [64, 64],
        spineCtl: [50, 58],
        armA: [[38, 58], [31, 75], [28, 92]],
        legA: [[64, 64], [86, 66], [90, 92]],
      },
    ],
  },

  // Downward dog: hips high, spine long, chest pressed back toward the thighs,
  // heels reaching for the floor.
  "down-dog": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [40, 48],
        neck: [46, 44],
        hip: [76, 22],
        armA: [[46, 44], [36, 66], [27, 90]],
        legA: [[76, 22], [86, 56], [92, 91]],
        legB: [[76, 23], [83, 57], [88, 91]],
      },
    ],
  },

  // Bretzel: side-lying twist — top knee stays down at 90 in front, bottom
  // heel pulled to the butt, top shoulder rotating back toward the floor.
  "bretzel": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [26, 64],
        neck: [37, 70],
        hip: [72, 82],
        armA: [[37, 70], [48, 62], [59, 55]],
        legA: [[72, 82], [52, 88], [37, 90]],
        legB: [[72, 82], [92, 84], [85, 65]],
      },
    ],
  },

  // Seated 90/90: front shin across the body, back shin turned in behind,
  // torso stacked tall over the hips.
  "ninety-ninety": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [44, 24],
        neck: [46, 34],
        hip: [50, 66],
        armA: [[46, 36], [64, 50], [80, 58]],
        legA: [[50, 66], [78, 74], [96, 86]],
        legB: [[50, 66], [30, 78], [18, 88]],
      },
    ],
  },

  // Butcher's block: kneeling with the elbows up on a bench, chest falling
  // through toward the floor while the spine stays hollow.
  "butchers-block": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [26, 50],
        neck: [37, 53],
        hip: [77, 52],
        armA: [[37, 53], [27, 57], [16, 60]],
        legA: [[77, 52], [82, 72], [72, 91]],
        legB: [[77, 53], [86, 72], [78, 91]],
      },
    ],
  },

  // Basic crawl: quadruped with the knees just off the floor, opposite hand
  // and foot swapping forward.
  "crawl": {
    props: FLOOR,
    frames: [
      {
        head: [22, 52],
        neck: [34, 56],
        hip: [78, 60],
        armA: [[34, 56], [30, 73], [26, 89]],
        armB: [[34, 56], [46, 68], [56, 80]],
        legA: [[78, 60], [88, 74], [94, 89]],
        legB: [[78, 60], [68, 70], [60, 82]],
      },
      {
        head: [22, 52],
        neck: [34, 56],
        hip: [78, 60],
        armA: [[34, 56], [40, 70], [46, 84]],
        armB: [[34, 56], [34, 74], [34, 89]],
        legA: [[78, 60], [82, 76], [86, 89]],
        legB: [[78, 60], [74, 68], [68, 78]],
      },
    ],
  },

  // ---- soft tissue -------------------------------------------------------

  // Quads on the roller: prone, propped on the forearms, rolling thigh to hip.
  "foamroll-quad": {
    motion: "roll",
    props: [{ kind: "floor" }, { kind: "roller", at: [72, 85] }],
    frames: [
      {
        head: [29, 64],
        neck: [39, 71],
        hip: [62, 76],
        armA: [[39, 72], [33, 82], [30, 90]],
        legA: [[62, 76], [82, 83], [101, 87]],
      },
    ],
  },

  // Hamstrings on the roller: seated, hands behind, weight through the thigh.
  "foamroll-hamstring": {
    motion: "roll",
    props: [{ kind: "floor" }, { kind: "roller", at: [73, 85] }],
    frames: [
      {
        head: [38, 45],
        neck: [42, 55],
        hip: [47, 80],
        armA: [[42, 57], [32, 72], [25, 88]],
        legA: [[47, 80], [72, 78], [95, 84]],
      },
    ],
  },

  // IT band / outer thigh: side-lying, propped on one forearm.
  "foamroll-itband": {
    motion: "roll",
    props: [{ kind: "floor" }, { kind: "roller", at: [77, 85] }],
    frames: [
      {
        head: [22, 60],
        neck: [33, 68],
        hip: [58, 78],
        armA: [[33, 69], [27, 81], [25, 90]],
        legA: [[58, 78], [78, 79], [97, 84]],
      },
    ],
  },

  // Thoracic spine: roller under the upper back, hips lifted, arms crossed.
  "foamroll-back": {
    motion: "roll",
    props: [{ kind: "floor" }, { kind: "roller", at: [38, 79] }],
    frames: [
      {
        head: [24, 60],
        neck: [34, 67],
        hip: [64, 73],
        armA: [[37, 69], [50, 64], [59, 71]],
        legA: [[64, 73], [82, 62], [82, 91]],
      },
    ],
  },

  // Calves: seated, one calf over the roller, hands behind for lift.
  "foamroll-calf": {
    motion: "roll",
    props: [{ kind: "floor" }, { kind: "roller", at: [84, 86] }],
    frames: [
      {
        head: [36, 45],
        neck: [40, 55],
        hip: [45, 80],
        armA: [[40, 57], [30, 72], [23, 88]],
        legA: [[45, 80], [64, 78], [96, 81]],
      },
    ],
  },

  // Lacrosse ball in the glute: seated on the ball, ankle crossed over the knee.
  "ball-glute": {
    motion: "roll",
    props: [{ kind: "floor" }, { kind: "roller", at: [58, 87], r: 5 }],
    frames: [
      {
        head: [40, 46],
        headR: 6,
        neck: [46, 56],
        hip: [58, 80],
        armB: [[46, 58], [33, 72], [26, 88]],
        legA: [[58, 80], [82, 74], [90, 90]],
        legB: [[58, 80], [74, 60], [58, 68]],
      },
    ],
  },

  // ---- breathing ---------------------------------------------------------

  // Diaphragmatic breathing on the back, knees bent, a hand on the belly.
  "breathing-supine": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [19, 72],
        neck: [31, 78],
        hip: [64, 85],
        armA: [[32, 78], [43, 69], [56, 78]],
        armB: [[32, 82], [44, 85], [54, 89]],
        legA: [[64, 85], [83, 60], [83, 91]],
      },
    ],
  },

  // Seated box breathing: cross-legged, tall spine, hands resting on the knees.
  "breathing-seated": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [60, 20],
        headR: 7,
        neck: [60, 32],
        hip: [60, 65],
        armA: [[51, 35], [45, 55], [43, 74]],
        armB: [[69, 35], [75, 55], [77, 74]],
        legA: [[60, 65], [40, 76], [62, 82]],
        legB: [[60, 65], [80, 76], [58, 82]],
      },
    ],
  },

  // ---- generic fallbacks -------------------------------------------------
  // Used when neither the coach's slug nor the drill name resolves. Each one
  // reads as "a person doing this modality" without claiming a specific drill.

  "generic-static": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [66, 34],
        neck: [60, 41],
        hip: [48, 56],
        armA: [[59, 43], [69, 58], [78, 72]],
        legA: [[48, 56], [64, 72], [80, 88]],
        legB: [[48, 56], [45, 74], [43, 92]],
      },
    ],
  },

  "generic-dynamic": {
    swing: ["legA"],
    props: FLOOR,
    frames: [
      {
        head: [54, 22],
        neck: [54, 31],
        hip: [54, 53],
        armA: [[48, 34], [37, 43], [26, 47]],
        armB: [[60, 34], [71, 43], [82, 47]],
        legA: [[54, 53], [62, 71], [70, 88]],
        legB: [[54, 53], [52, 73], [50, 92]],
      },
    ],
  },

  "generic-foamroll": {
    motion: "roll",
    props: [{ kind: "floor" }, { kind: "roller", at: [72, 85] }],
    frames: [
      {
        head: [29, 64],
        neck: [39, 71],
        hip: [62, 76],
        armA: [[39, 72], [33, 82], [30, 90]],
        legA: [[62, 76], [82, 83], [101, 87]],
      },
    ],
  },

  "generic-breathing": {
    motion: "breathe",
    props: FLOOR,
    frames: [
      {
        head: [60, 20],
        headR: 7,
        neck: [60, 32],
        hip: [60, 65],
        armA: [[51, 35], [45, 55], [43, 74]],
        armB: [[69, 35], [75, 55], [77, 74]],
        legA: [[60, 65], [40, 76], [62, 82]],
        legB: [[60, 65], [80, 76], [58, 82]],
      },
    ],
  },
};

// Name keywords → pose, for when the coach names a drill but omits the slug.
// Order matters: the FIRST entry whose keyword appears in the lowercased name
// wins, so the more specific phrases come first ("foam roll quad" must beat a
// bare "quad").
const KEYWORDS: [string[], StretchPose][] = [
  // soft tissue first — these names usually also contain a muscle word that a
  // later static-stretch rule would otherwise claim.
  [["it band", "itband", "iliotibial", "tfl", "outer thigh"], "foamroll-itband"],
  [["thoracic roll", "upper back roll", "t-spine roll", "roll your back", "back roll"], "foamroll-back"],
  [["glute ball", "lacrosse", "tennis ball", "glute smash", "piriformis release"], "ball-glute"],
  // breathing
  [["box breath", "breathing", "breathe", "breath work", "breathwork", "diaphragm"], "breathing-supine"],
  // dynamic
  [["cat-cow", "cat cow", "cat camel"], "cat-cow"],
  [["world's greatest", "worlds greatest", "spiderman"], "worlds-greatest"],
  [["leg swing", "leg swings"], "leg-swing"],
  [["arm circle", "shoulder circle"], "arm-circles"],
  [["hip car", "hip circle", "hip cars", "90/90 switch", "knee circle"], "hip-cars"],
  [["open book", "thoracic rotation", "t-spine rotation", "windmill"], "open-book"],
  [["deep squat", "squat hold", "malasana", "third world squat", "cossack"], "deep-squat"],
  [["glute bridge", "hip bridge", "bridge"], "glute-bridge"],
  [["pass-through", "pass through", "shoulder dislocate", "band dislocate"], "shoulder-pass-through"],
  [["hang", "dead hang", "bar hang"], "bar-hang"],
  [["crab", "reverse plank", "table top", "tabletop"], "crab-bridge"],
  [["down dog", "downward dog", "down-dog", "adho mukha"], "down-dog"],
  [["bretzel"], "bretzel"],
  [["90/90", "90-90", "ninety"], "ninety-ninety"],
  [["butcher"], "butchers-block"],
  [["crawl"], "crawl"],
  // static
  [["figure-4", "figure 4", "figure four"], "figure-4"],
  [["pigeon", "90/90", "lizard"], "pigeon"],
  [["child", "balasana"], "child-pose"],
  [["couch stretch", "hip flexor", "kneeling lunge", "quad stretch", "psoas"], "hip-flexor-lunge"],
  [["doorway", "pec ", "pectoral", "chest stretch", "chest opener"], "chest-doorway"],
  [["tricep", "lat stretch overhead", "overhead reach"], "overhead-triceps"],
  [["neck", "upper trap", "levator", "scalene"], "neck-lateral"],
  [["calf", "gastroc", "soleus", "achilles", "ankle dorsiflex"], "calf-wall"],
  [["butterfly", "adductor", "groin", "straddle", "frog"], "butterfly"],
  [["seated twist", "spinal twist", "twist"], "seated-twist"],
  [["supine twist", "lying twist", "scorpion"], "supine-twist"],
  [["cobra", "sphinx", "extension", "press-up", "mckenzie"], "cobra"],
  [["side bend", "lat stretch", "lat ", "side body", "quadratus", "qL "], "side-bend"],
  [["hamstring", "toe touch", "forward fold", "pike", "good morning stretch"], "hamstring-hinge"],
  // muscle-only names that still imply a roller when paired with roll words
  [["quad"], "foamroll-quad"],
  [["glute", "hip stretch", "piriformis"], "figure-4"],
];

const ROLL_WORDS = ["foam roll", "foam-roll", "roller", "roll ", "smr", "release", "smash"];

const GENERIC: Record<string, StretchPose> = {
  static: "generic-static",
  dynamic: "generic-dynamic",
  // Loaded work is movement under load — the dynamic figure reads closer than
  // a passive hold when no specific pose matches.
  loaded: "generic-dynamic",
  foamroll: "generic-foamroll",
  breathing: "generic-breathing",
};

// Roller variants keyed by the muscle a rolling drill names, so "foam roll
// your hamstrings" lands on the seated roller figure rather than the standing
// hamstring stretch.
const ROLL_TARGETS: [string[], StretchPose][] = [
  [["hamstring"], "foamroll-hamstring"],
  [["quad", "thigh", "hip flexor"], "foamroll-quad"],
  [["it band", "itband", "outer"], "foamroll-itband"],
  [["calf", "gastroc", "soleus"], "foamroll-calf"],
  [["back", "thoracic", "t-spine", "lat"], "foamroll-back"],
  [["glute", "piriformis", "hip"], "ball-glute"],
];

export function isStretchPose(v: unknown): v is StretchPose {
  return typeof v === "string" && POSE_SET.has(v);
}

// Normalize whatever the model put in `pose` (case/spacing/underscore drift)
// onto a known slug, or null if it isn't one of ours.
export function coercePose(v: unknown): StretchPose | null {
  if (typeof v !== "string") return null;
  const k = v.trim().toLowerCase().replace(/[\s_]+/g, "-");
  return POSE_SET.has(k) ? (k as StretchPose) : null;
}

// The whole resolution chain: explicit slug → name keywords → modality
// fallback. Always returns a renderable pose so no step is ever blank.
export function resolvePose(
  pose: StretchPose | null | undefined,
  name: string,
  kind: string | null | undefined,
): StretchPose {
  if (pose && POSE_SET.has(pose)) return pose;

  const n = (name || "").toLowerCase();

  // A rolling/release drill: pick the roller figure for whatever it targets.
  if (ROLL_WORDS.some((w) => n.includes(w)) || kind === "foamroll") {
    for (const [words, p] of ROLL_TARGETS) {
      if (words.some((w) => n.includes(w))) return p;
    }
  }

  for (const [words, p] of KEYWORDS) {
    if (words.some((w) => n.includes(w))) return p;
  }

  return GENERIC[kind ?? "static"] ?? "generic-static";
}
